version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.6-management-alpine"
    hostname: "rabbitmq-1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq-1"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
